services:
  matlab:
    image: mathworks/matlab:r2022b
    shm_size: 512M
    environment:
      - MLM_LICENSE_FILE = ./Matlab/license.lic
    command: /bin/run.sh -browser
    expose:
      - 10001
      - 10002
      - 10003
      - 10004
    ports:
      - 8888:8888
    networks:
      - ics

  simlink:
    build: ./OpenPLC_Simulink
    expose:
      - 6668
      - 10001
      - 10002
      - 10003
      - 10004
    networks:
      - ics

  openplc:
    build: ./OpenPLC_v3
    expose:
      - 6668
    ports:
      - 8080:8080
    networks:
      - ics

networks:
  ics:
    driver: bridge