services:
  matlab:
    build: ./Matlab
    shm_size: 512M
    environment:
      - MLM_LICENSE_FILE = ./Matlab/license.lic
    command: /bin/run.sh -browser
    ports:
      - 8888:8888
      - 10001:10001
      - 10002:10002
      - 10003:10003
      - 10004:10004
    volumes:
      - ./Matlab/Water_Tank:/home/matlab/Documents/MATLAB/Water_Tank
  openplc:
    build: ./OpenPLC_v3
    ports:
      - 8080:8080
      - 6668:6668
    
volumes:
  Water_Tank: