services:
  # matlab:
  #   build: ./Matlab
  #   shm_size: 512M
  #   environment:
  #     - MLM_LICENSE_FILE = ./Matlab/license.lic
  #   command: /bin/run.sh -browser
  #   ports:
  #     - 8888:8888
  #     - 10001:10001
  #     - 10002:10002
  #     - 10003:10003
  #     - 10004:10004
  #   volumes:
  #     - ./Matlab/Water_Tank:/home/matlab/Documents/MATLAB/Water_Tank
  
  simlink:
    build: ./OpenPLC_Simulink
    expose:
      - 6668
    networks:
      - ics

  openplc:
    build: ./OpenPLC_v3
    expose:
      - 6668
    ports:
      - 8080:8080
      - 10001:10001
      - 10002:10002
      - 10003:10003
      - 10004:10004
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ics
    
volumes:
  Water_Tank:

networks:
  ics:
    driver: bridge